### ISSUE TITLE
locale setting causing trending to show error.

### ISSUE THREAD

**Issue by yvan** [SMAPPNYU/smappboard#10]
Traceback (most recent call last):
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yvan/smapprepos/smappboard/smappboard/app.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/home/yvan/smapprepos/smappboard/smappboard/app.py", line 168, in get_current_worlwide_trends
    locale.setlocale(locale.LC_ALL, 'en_US')
  File "/home/yvan/miniconda/envs/smappboard/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by yvan** [comment]
removed locale as a way of formatting numbers.
